package htcondor

import (
	"context"
	"fmt"
	"strings"

	"github.com/PelicanPlatform/classad/classad"
	"github.com/bbockelm/cedar/client"
	"github.com/bbockelm/cedar/commands"
	"github.com/bbockelm/cedar/message"
)

// JobAction represents an action to perform on jobs
type JobAction int

// Job action constants based on HTCondor's JobAction enum.
//
// These values are placed on the wire as ATTR_JOB_ACTION and MUST match the
// C++ enum exactly (src/condor_utils/enum_utils.h:106-116):
//
//	JA_ERROR = 0, JA_HOLD_JOBS, JA_RELEASE_JOBS, JA_REMOVE_JOBS,
//	JA_REMOVE_X_JOBS, JA_VACATE_JOBS, JA_VACATE_FAST_JOBS,
//	JA_CLEAR_DIRTY_JOB_ATTRS, JA_SUSPEND_JOBS, JA_CONTINUE_JOBS,
//	JA_TRANSFER_AND_REMOVE_JOBS
//
// (An earlier version of this file omitted JA_CLEAR_DIRTY_JOB_ATTRS, which
// silently shifted JA_SUSPEND_JOBS/JA_CONTINUE_JOBS off by one relative to the
// schedd's switch in Scheduler::actOnJobs, src/condor_schedd.V6/schedd.cpp:7517.)
//
//nolint:revive // Constant names match HTCondor's C++ enum naming convention
const (
	JA_ERROR                    JobAction = iota // 0: Error/invalid action
	JA_HOLD_JOBS                                 // 1: Hold jobs
	JA_RELEASE_JOBS                              // 2: Release held jobs
	JA_REMOVE_JOBS                               // 3: Remove jobs
	JA_REMOVE_X_JOBS                             // 4: Remove jobs with force (X = extended/force)
	JA_VACATE_JOBS                               // 5: Vacate jobs (gentle)
	JA_VACATE_FAST_JOBS                          // 6: Vacate jobs (fast/hard kill)
	JA_CLEAR_DIRTY_JOB_ATTRS                     // 7: Clear dirty job attributes
	JA_SUSPEND_JOBS                              // 8: Suspend jobs
	JA_CONTINUE_JOBS                             // 9: Continue suspended jobs
	JA_TRANSFER_AND_REMOVE_JOBS                  // 10: Spool then remove jobs
)

// ActionResultType specifies what kind of result information to return
type ActionResultType int

// Action result type constants.
//
// Placed on the wire as ATTR_ACTION_RESULT_TYPE. MUST match the C++
// action_result_type_t enum (src/condor_daemon_client/dc_schedd.h:63-67):
//
//	AR_NONE = 0  // don't care / don't yet know
//	AR_LONG = 1  // want info per job (job_<c>_<p> / cluster_<c> = result)
//	AR_TOTALS = 2 // want totals for each possible result (result_total_<N>)
//
// The schedd only special-cases AR_LONG; anything else is treated as AR_TOTALS
// (src/condor_schedd.V6/schedd.cpp:7571-7574). The earlier Go values had
// AR_TOTALS=0, which happened to work but did not match the C++ enum.
//
//nolint:revive // Constant names match HTCondor's C++ enum naming convention
const (
	AR_NONE   ActionResultType = iota // 0: don't care / don't yet know
	AR_LONG                           // 1: Return detailed per-job results
	AR_TOTALS                         // 2: Return only totals (default)
)

// ActionResult represents the result of an action on a single job
type ActionResult int

// Action result constants.
//
// These index the result ad's per-result attributes
// (result_total_<N> for AR_TOTALS, job_<c>_<p>/cluster_<c> = <N> for AR_LONG).
// MUST match the C++ action_result_t enum (src/condor_daemon_client/dc_schedd.h:52-60).
//
//nolint:revive // Constant names match HTCondor's C++ enum naming convention
const (
	AR_ERROR             ActionResult = iota // 0: Error occurred (no longer generated by the schedd as of 2025)
	AR_SUCCESS                               // 1: Action succeeded
	AR_NOT_FOUND                             // 2: Job not found
	AR_BAD_STATUS                            // 3: Job in wrong status for action
	AR_ALREADY_DONE                          // 4: Action already performed
	AR_PERMISSION_DENIED                     // 5: Permission denied
	AR_LIMIT_EXCEEDED                        // 6: Per-user job/action limit exceeded
)

// JobActionResults contains the results of a job action
type JobActionResults struct {
	// Total count of each result type
	TotalJobs        int
	Success          int
	NotFound         int
	PermissionDenied int
	BadStatus        int
	AlreadyDone      int
	LimitExceeded    int
	Error            int

	// The result ClassAd from the schedd (may contain per-job details)
	ResultAd *classad.ClassAd
}

// RemoveJobs removes jobs matching the constraint
// constraint is a ClassAd constraint expression
// reason is an optional reason for the removal (can be empty string)
func (s *Schedd) RemoveJobs(ctx context.Context, constraint string, reason string) (*JobActionResults, error) {
	if constraint == "" {
		return nil, fmt.Errorf("constraint cannot be empty")
	}

	return s.actOnJobs(ctx, JA_REMOVE_JOBS, constraint, nil, reason, "RemoveReason", "", "", AR_TOTALS)
}

// RemoveJobsByID removes specific jobs by their cluster.proc IDs
// ids is a slice of job IDs in "cluster.proc" format (e.g., []string{"123.0", "123.1"})
// reason is an optional reason for the removal (can be empty string)
func (s *Schedd) RemoveJobsByID(ctx context.Context, ids []string, reason string) (*JobActionResults, error) {
	if len(ids) == 0 {
		return nil, fmt.Errorf("ids cannot be empty")
	}

	return s.actOnJobs(ctx, JA_REMOVE_JOBS, "", ids, reason, "RemoveReason", "", "", AR_TOTALS)
}

// HoldJobs holds jobs matching the constraint
func (s *Schedd) HoldJobs(ctx context.Context, constraint string, reason string) (*JobActionResults, error) {
	if constraint == "" {
		return nil, fmt.Errorf("constraint cannot be empty")
	}

	return s.actOnJobs(ctx, JA_HOLD_JOBS, constraint, nil, reason, "HoldReason", "", "", AR_TOTALS)
}

// ReleaseJobs releases held jobs matching the constraint
func (s *Schedd) ReleaseJobs(ctx context.Context, constraint string, reason string) (*JobActionResults, error) {
	if constraint == "" {
		return nil, fmt.Errorf("constraint cannot be empty")
	}

	return s.actOnJobs(ctx, JA_RELEASE_JOBS, constraint, nil, reason, "ReleaseReason", "", "", AR_TOTALS)
}

// actOnJobs implements the ACT_ON_JOBS protocol
// This is based on DCSchedd::actOnJobs in HTCondor
//
//nolint:unparam // Parameters reserved for future actions and result types
func (s *Schedd) actOnJobs(
	ctx context.Context,
	action JobAction,
	constraint string,
	ids []string,
	reason string,
	reasonAttr string,
	reasonCode string,
	reasonCodeAttr string,
	resultType ActionResultType,
) (*JobActionResults, error) {
	// Validate parameters
	if constraint != "" && len(ids) > 0 {
		return nil, fmt.Errorf("cannot specify both constraint and ids")
	}
	if constraint == "" && len(ids) == 0 {
		return nil, fmt.Errorf("must specify either constraint or ids")
	}

	// Get SecurityConfig from context, HTCondor config, or defaults
	secConfig, err := GetSecurityConfigOrDefault(ctx, nil, commands.ACT_ON_JOBS, "CLIENT", s.address)
	if err != nil {
		return nil, fmt.Errorf("failed to create security config: %w", err)
	}

	// Connect to schedd and authenticate using cedar client
	// This handles session resumption failures automatically
	htcondorClient, err := client.ConnectAndAuthenticate(ctx, s.address, secConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to connect and authenticate to schedd: %w", err)
	}
	defer func() {
		_ = htcondorClient.Close()
	}()

	// Get CEDAR stream from client
	cedarStream := htcondorClient.GetStream()

	// Build command ClassAd
	cmdAd := classad.New()
	_ = cmdAd.Set("JobAction", int64(action))
	_ = cmdAd.Set("ActionResultType", int64(resultType))

	if constraint != "" {
		// Insert constraint as an expression
		constraintExpr, err := classad.ParseExpr(constraint)
		if err != nil {
			return nil, fmt.Errorf("invalid constraint expression: %w", err)
		}
		_ = cmdAd.Set("ActionConstraint", constraintExpr)
	} else if len(ids) > 0 {
		// Join IDs as comma-separated string
		idsStr := strings.Join(ids, ",")
		_ = cmdAd.Set("ActionIds", idsStr)
	}

	if reasonAttr != "" && reason != "" {
		_ = cmdAd.Set(reasonAttr, reason)
	}

	if reasonCodeAttr != "" && reasonCode != "" {
		// Reason code is an expression
		codeExpr, err := classad.ParseExpr(reasonCode)
		if err != nil {
			return nil, fmt.Errorf("invalid reason code expression: %w", err)
		}
		_ = cmdAd.Set(reasonCodeAttr, codeExpr)
	}

	// Send command ClassAd
	msg := message.NewMessageForStream(cedarStream)
	if err := msg.PutClassAd(ctx, cmdAd); err != nil {
		return nil, fmt.Errorf("failed to send command ad: %w", err)
	}
	if err := msg.FinishMessage(ctx); err != nil {
		return nil, fmt.Errorf("failed to finish message: %w", err)
	}

	// Read response ClassAd
	responseMsg := message.NewMessageFromStream(cedarStream)
	resultAd, err := responseMsg.GetClassAd(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to read response ad: %w", err)
	}

	// Check if action failed
	actionResult, ok := resultAd.EvaluateAttrInt("ActionResult")
	if !ok || actionResult != 1 { // OK = 1
		// Action failed, return results anyway so caller can see what went wrong
		return parseJobActionResults(resultAd), fmt.Errorf("action failed: result=%d", actionResult)
	}

	// Phase 2 of the ACT_ON_JOBS handshake. The schedd only reaches this point
	// when it acted on at least one job (num_success > 0); otherwise it aborts
	// its transaction and closes the stream after phase 1
	// (src/condor_schedd.V6/schedd.cpp:8035-8047).
	//
	// Tell the schedd we're still here and ready to commit. In C++ this is
	//   rsock.encode(); int answer = OK; rsock.code(answer); rsock.end_of_message();
	// (src/condor_daemon_client/dc_schedd.cpp:1351-1353). Note that
	// Stream::code(int&) -> Stream::put(int) promotes the int to a 64-bit value
	// on the wire (src/condor_io/stream.cpp:557 -> :586), so this is an 8-byte
	// field, not 4. Use PutInt (64-bit) rather than PutInt32 to mirror the C++
	// int exactly.
	ackMsg := message.NewMessageForStream(cedarStream)
	if err := ackMsg.PutInt(ctx, 1); err != nil { // OK = 1
		return nil, fmt.Errorf("failed to send acknowledgment: %w", err)
	}
	if err := ackMsg.FinishMessage(ctx); err != nil {
		return nil, fmt.Errorf("failed to finish acknowledgment: %w", err)
	}

	// Read the schedd's final confirmation that the commit succeeded. In C++:
	//   rsock.decode(); rsock.code(reply); rsock.end_of_message();
	// (src/condor_daemon_client/dc_schedd.cpp:1365-1366) where reply is an int,
	// so again an 8-byte field on the wire. The schedd writes it with
	//   rsock->encode(); int answer = OK; rsock->code(answer); end_of_message();
	// (src/condor_schedd.V6/schedd.cpp:8075-8080).
	confirmMsg := message.NewMessageFromStream(cedarStream)
	confirmation, err := confirmMsg.GetInt(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to read confirmation: %w", err)
	}
	if confirmation != 1 { // OK = 1
		return parseJobActionResults(resultAd), fmt.Errorf("schedd failed to commit changes: result=%d", confirmation)
	}

	// Parse and return results
	return parseJobActionResults(resultAd), nil
}

// parseJobActionResults extracts job action results from the result ClassAd
func parseJobActionResults(resultAd *classad.ClassAd) *JobActionResults {
	results := &JobActionResults{
		ResultAd: resultAd,
	}

	// HTCondor uses indexed result attributes: result_total_0, result_total_1, etc.
	// where the index corresponds to the ActionResult enum value:
	// AR_ERROR = 0, AR_SUCCESS = 1, AR_NOT_FOUND = 2, AR_BAD_STATUS = 3,
	// AR_ALREADY_DONE = 4, AR_PERMISSION_DENIED = 5, AR_LIMIT_EXCEEDED = 6
	// (JobActionResults::publishResults, src/condor_daemon_client/dc_schedd.cpp:1524)

	// Extract indexed results
	if val, ok := resultAd.EvaluateAttrInt("result_total_0"); ok {
		results.Error = int(val)
	}
	if val, ok := resultAd.EvaluateAttrInt("result_total_1"); ok {
		results.Success = int(val)
	}
	if val, ok := resultAd.EvaluateAttrInt("result_total_2"); ok {
		results.NotFound = int(val)
	}
	if val, ok := resultAd.EvaluateAttrInt("result_total_3"); ok {
		results.BadStatus = int(val)
	}
	if val, ok := resultAd.EvaluateAttrInt("result_total_4"); ok {
		results.AlreadyDone = int(val)
	}
	if val, ok := resultAd.EvaluateAttrInt("result_total_5"); ok {
		results.PermissionDenied = int(val)
	}
	if val, ok := resultAd.EvaluateAttrInt("result_total_6"); ok {
		results.LimitExceeded = int(val)
	}

	// Calculate total jobs acted on
	results.TotalJobs = results.Error + results.Success + results.NotFound +
		results.BadStatus + results.AlreadyDone + results.PermissionDenied +
		results.LimitExceeded

	// Also check for TotalJobAds attribute which gives total jobs considered
	if val, ok := resultAd.EvaluateAttrInt("TotalJobAds"); ok {
		// Use this as the total if it's available and larger
		if int(val) > results.TotalJobs {
			results.TotalJobs = int(val)
		}
	}

	return results
}
