// Package vscode builds the HTCondor job that runs a VS Code server
// inside a sandbox, reached through the API server's job proxy.
//
// The server listens on a Unix socket in the job's scratch directory,
// never on a TCP port. A port bound to 127.0.0.1 in a sandbox is
// reachable by any local user on the execute node unless the job has
// its own network namespace, which no pool can be assumed to
// configure; a socket is protected by file permissions. That is also
// why the server runs with authentication disabled and no secret is
// minted anywhere in this design: the socket's permissions ARE the
// authorization, and reaching it at all requires the schedd to agree
// the caller owns the job.
package vscode

import (
	"fmt"
	"strings"
	"time"
)

// BatchPrefix marks a job as a VS Code session by JobBatchName.
//
// JobBatchName rather than a custom attribute, following the
// interactive package: it is what `condor_q -batch` already displays,
// so a user sees their sessions in the queue without being told where
// to look.
const BatchPrefix = "htcondor-api-vscode-"

// SocketName is the socket the server listens on, relative to the
// job's scratch directory. The proxy addresses a session by it, so it
// is part of the URL and cannot vary per session without the caller
// being told.
const SocketName = "vscode.sock"

// MaxSocketPath is the practical ceiling on a Unix socket address.
// sun_path is 108 bytes on Linux and 104 on macOS, and both ends of an
// SSH forward are bound by it. An HTCondor scratch directory can fill
// most of that on its own, and the kernel's complaint is an
// uninformative "open failed" at the far end -- so the launcher checks
// it in the sandbox, where the real path is known, and refuses to
// start rather than leaving the proxy to report a mystery.
const MaxSocketPath = 100

// DefaultServerCommand is the program the launcher execs. Anything
// that serves the VS Code UI over a Unix socket and emits relative
// URLs will do: code-server and openvscode-server both qualify, and
// neither can be told the path it is served under, which is why the
// proxy strips its prefix and redirects to a trailing slash.
const DefaultServerCommand = "code-server"

// ScriptArgs configures the in-sandbox launcher.
type ScriptArgs struct {
	// ServerCommand is the program to exec. Empty means
	// DefaultServerCommand.
	ServerCommand string

	// Workdir is the folder the editor opens, relative to the scratch
	// directory when not absolute. Empty means the scratch directory.
	Workdir string

	// ExtraArgs are appended to the server command verbatim.
	ExtraArgs []string
}

// LaunchScript renders the shell script that runs inside the job.
//
// It is transferred as a file rather than passed as a command, because
// anything sent through condor_ssh_to_job is word-split on IFS and
// rejoined with spaces (condor_ssh_to_job_shell_setup runs `eval
// ${SSH_ORIGINAL_COMMAND}` unquoted), so a multi-line script would
// arrive as one line. Here it is the job's executable, which has no
// such problem -- but the constraint is worth remembering for anything
// this grows into.
func LaunchScript(a ScriptArgs) string {
	cmd := a.ServerCommand
	if cmd == "" {
		cmd = DefaultServerCommand
	}
	workdir := a.Workdir
	if workdir == "" {
		workdir = "."
	}

	var extra string
	if len(a.ExtraArgs) > 0 {
		extra = " " + strings.Join(a.ExtraArgs, " ")
	}

	return fmt.Sprintf(`#!/bin/sh
# Auto-generated by htcondor-api. Runs a VS Code server on a Unix
# socket in this job's scratch directory.
set -eu

SCRATCH="${_CONDOR_SCRATCH_DIR:-$PWD}"
SOCK="$SCRATCH/%[2]s"

# Fail here, with the path, rather than at the far end of a forward.
# A Unix socket address is capped at ~%[3]d bytes; an EXECUTE directory
# deep enough to blow that makes every connection fail with nothing
# more informative than "open failed".
LEN=$(printf '%%s' "$SOCK" | wc -c | tr -d ' ')
if [ "$LEN" -gt %[3]d ]; then
	echo "vscode: socket path is $LEN bytes, over the ~%[3]d a Unix socket allows:" >&2
	echo "  $SOCK" >&2
	echo "vscode: this pool's EXECUTE directory is too deep to serve a session over a socket" >&2
	exit 1
fi

if ! command -v %[1]s >/dev/null 2>&1; then
	echo "vscode: %[1]s is not installed in this job's environment" >&2
	echo "vscode: use a container image that provides it, or install it in the job" >&2
	exit 1
fi

# The socket's permissions are the authorization -- the server runs
# with auth disabled because nothing else can open it. umask rather
# than a chmod after the fact: there is no moment where the socket
# exists and is world-writable.
umask 077
rm -f "$SOCK"

cd "$SCRATCH"
exec %[1]s \
	--auth none \
	--disable-telemetry \
	--disable-update-check \
	--socket "$SOCK"%[5]s \
	%[4]s
`, cmd, SocketName, MaxSocketPath, shellQuote(workdir), extra)
}

// shellQuote wraps s for /bin/sh. The workdir reaches here from a
// caller, and an unquoted one would be a command injection into the
// job's own executable.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// SubmitArgs configures the session job.
type SubmitArgs struct {
	// SessionID names the session; it goes in the JobBatchName.
	SessionID string

	// Universe is "container" or "vanilla". A container image is the
	// practical choice, since the server has to come from somewhere.
	Universe string
	Image    string

	Cpus     int
	MemoryMB int
	DiskMB   int

	// MaxLifetime is the ceiling the sandbox cannot talk its way out
	// of. Zero means no ceiling, which is almost never what an
	// operator wants -- see PeriodicRemoveExpr.
	MaxLifetime time.Duration

	// ExtraRequirements is the operator's interactive-requirements
	// expression, ANDed with ours.
	ExtraRequirements string

	// CallerSubmitLines are the user's own submit commands; validated
	// by the caller. ExtraSubmitLines are the operator's, appended
	// last so operator policy wins.
	CallerSubmitLines string
	ExtraSubmitLines  string
}

// BatchName is the JobBatchName for a session.
func BatchName(sessionID string) string { return BatchPrefix + sessionID }

// SessionIDFromBatchName recovers a session id, reporting false for a
// job that is not one of ours.
func SessionIDFromBatchName(batchName string) (string, bool) {
	if !strings.HasPrefix(batchName, BatchPrefix) {
		return "", false
	}
	id := strings.TrimPrefix(batchName, BatchPrefix)
	if id == "" {
		return "", false
	}
	return id, true
}

// PeriodicRemoveExpr is the lifetime ceiling.
//
// It has to be the schedd's job, not the sandbox's. Traffic through
// the session is not a liveness signal: an editor left open in a
// browser talks to its server forever whether or not a human is there,
// so an idle timer measured on the wire reaps a closed tab and never
// an abandoned one. periodic_remove is evaluated by the schedd and
// holds whatever the sandbox, the server or the browser are doing.
func PeriodicRemoveExpr(d time.Duration) string {
	if d <= 0 {
		return ""
	}
	return fmt.Sprintf("periodic_remove = (time() - JobStartDate) > %d", int(d.Seconds()))
}

// ExecutableName is the launcher script's name in the sandbox.
const ExecutableName = "vscode-launch.sh"

// BuildSubmitFile renders the session job.
func BuildSubmitFile(a SubmitArgs) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Auto-generated by htcondor-api for VS Code session %s\n", a.SessionID)

	switch a.Universe {
	case "container":
		fmt.Fprintf(&sb, "universe = container\n")
		// An explicit scheme, or HTCondor reads a bare "repo:tag" as a
		// sandbox directory (image_type_from_string).
		fmt.Fprintf(&sb, "container_image = %s\n\n", containerImageRef(a.Image))
	default:
		// Vanilla: the server has to already be on the execute node,
		// which is the launcher's `command -v` check.
		fmt.Fprintf(&sb, "universe = vanilla\n\n")
	}

	fmt.Fprintf(&sb, "executable = %s\n", ExecutableName)
	fmt.Fprintf(&sb, "transfer_executable = true\n\n")
	fmt.Fprintf(&sb, "should_transfer_files = YES\n")
	fmt.Fprintf(&sb, "when_to_transfer_output = ON_EXIT\n\n")

	if a.Cpus > 0 {
		fmt.Fprintf(&sb, "request_cpus = %d\n", a.Cpus)
	}
	if a.MemoryMB > 0 {
		fmt.Fprintf(&sb, "request_memory = %d\n", a.MemoryMB)
	}
	if a.DiskMB > 0 {
		fmt.Fprintf(&sb, "request_disk = %d\n", a.DiskMB)
	}
	sb.WriteString("\n")

	if extra := strings.TrimSpace(a.ExtraRequirements); extra != "" {
		fmt.Fprintf(&sb, "requirements = %s\n\n", extra)
	}

	// Name the batch so the queue says what this job is. Without it a
	// session shows up as a bare vscode-launch.sh among the user's real
	// work, which is what made the Jupyter ones look strange.
	fmt.Fprintf(&sb, "batch_name = %s\n", BatchName(a.SessionID))

	if expr := PeriodicRemoveExpr(a.MaxLifetime); expr != "" {
		fmt.Fprintf(&sb, "%s\n", expr)
	}

	fmt.Fprintf(&sb, "log    = vscode.log\n")
	fmt.Fprintf(&sb, "output = vscode.out\n")
	fmt.Fprintf(&sb, "error  = vscode.err\n")

	// The user's lines, then the operator's last so operator policy
	// overrides both the builder and the user.
	appendLines(&sb, a.CallerSubmitLines)
	appendLines(&sb, a.ExtraSubmitLines)

	fmt.Fprintf(&sb, "queue\n")
	return sb.String()
}

func appendLines(sb *strings.Builder, lines string) {
	for _, line := range strings.Split(lines, "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		sb.WriteString(line)
		sb.WriteString("\n")
	}
}

// containerImageRef gives a bare repo:tag an explicit scheme.
func containerImageRef(image string) string {
	if image == "" {
		return image
	}
	if strings.Contains(image, "://") || strings.HasSuffix(image, ".sif") ||
		strings.HasPrefix(image, "/") || strings.HasPrefix(image, "./") {
		return image
	}
	return "docker://" + image
}
