// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package config

import (
	"fmt"
	__yyfmt__ "fmt"
	"strings"
)

//line parser.y:2

// Statement represents a parsed configuration statement
type Statement interface {
	statement()
}

// Assignment represents a variable assignment
type Assignment struct {
	Name        string
	Value       string
	ClassAdExpr bool // True if this is a +Attribute = expr (ClassAd expression)
}

func (a *Assignment) statement() {}

// IncludeDirective represents an include statement
type IncludeDirective struct {
	Path string
	Type string // "include", "include_command", "include_ifexist"
}

func (i *IncludeDirective) statement() {}

// Conditional represents an if/elif/else/endif block
type Conditional struct {
	Condition   string
	ThenBlock   []Statement
	ElseIfBlock []ElseIf
	ElseBlock   []Statement
}

func (c *Conditional) statement() {}

// ElseIf represents an elif clause
type ElseIf struct {
	Condition string
	Block     []Statement
}

// UseDirective represents a use ROLE statement
type UseDirective struct {
	Role string
}

func (u *UseDirective) statement() {}

// ErrorDirective represents an error directive
type ErrorDirective struct {
	Message string
}

func (e *ErrorDirective) statement() {}

// WarningDirective represents a warning directive
type WarningDirective struct {
	Message string
}

func (w *WarningDirective) statement() {}

// QueueStatement represents a queue statement in submit files
type QueueStatement struct {
	Count    int      // Number of jobs to queue (0 means 1)
	VarNames []string // Variable names for iteration
	Items    []string // Items to iterate over (for "from" or "in" clauses)
	File     string   // Filename for "from" clause
	Slice    string   // Slice specification like [1:10]
}

func (q *QueueStatement) statement() {}

//line parser.y:82
type yySymType struct {
	yys     int
	str     string
	stmts   []Statement
	stmt    Statement
	elseifs []ElseIf
	elseif  ElseIf
	intval  int
	strlist []string
}

const IDENT = 57346
const STRING = 57347
const NUMBER = 57348
const ASSIGN = 57349
const IF = 57350
const ELIF = 57351
const ELSE = 57352
const ENDIF = 57353
const DEFINED = 57354
const VERSION = 57355
const INCLUDE = 57356
const USE = 57357
const TRUE = 57358
const FALSE = 57359
const YES = 57360
const NO = 57361
const ERROR = 57362
const WARNING = 57363
const IFEXIST = 57364
const COMMAND = 57365
const INTO = 57366
const QUEUE = 57367
const FROM = 57368
const IN = 57369
const MATCHING = 57370
const COLON = 57371
const LPAREN = 57372
const RPAREN = 57373
const LBRACK = 57374
const RBRACK = 57375
const COMMA = 57376
const PLUS = 57377
const EOF = 57378
const ILLEGAL = 57379
const COMMENT = 57380

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"STRING",
	"NUMBER",
	"ASSIGN",
	"IF",
	"ELIF",
	"ELSE",
	"ENDIF",
	"DEFINED",
	"VERSION",
	"INCLUDE",
	"USE",
	"TRUE",
	"FALSE",
	"YES",
	"NO",
	"ERROR",
	"WARNING",
	"IFEXIST",
	"COMMAND",
	"INTO",
	"QUEUE",
	"FROM",
	"IN",
	"MATCHING",
	"COLON",
	"LPAREN",
	"RPAREN",
	"LBRACK",
	"RBRACK",
	"COMMA",
	"PLUS",
	"EOF",
	"ILLEGAL",
	"COMMENT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:501

// parser holds the state for the parser
type parser struct {
	lexer  *Lexer
	result []Statement
	errors []error
}

// Lex is required by the goyacc-generated parser
func (p *parser) Lex(lval *yySymType) int {
	tok := p.lexer.NextToken()

	// Set the string value for tokens that have literal values
	switch tok.Token {
	case IDENT, STRING, NUMBER, ASSIGN:
		lval.str = tok.Lit
	}

	return int(tok.Token)
}

// Error is required by the goyacc-generated parser
func (p *parser) Error(s string) {
	p.errors = append(p.errors, fmt.Errorf("parse error: %s", s))
}

// Parse parses the input and returns the list of statements
func Parse(lexer *Lexer) ([]Statement, error) {
	p := &parser{
		lexer:  lexer,
		result: nil,
		errors: nil,
	}

	yyParse(p)

	// If we got results (even empty), return them if there were no critical errors
	// This allows graceful handling of minor syntax issues and empty input
	if p.result != nil {
		return p.result, nil
	}

	// If we have explicit errors, return the first one
	if len(p.errors) > 0 {
		return nil, p.errors[0]
	}

	// No result and no errors - return empty list for empty input
	return []Statement{}, nil
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 25,
	7, 20,
	-2, 36,
	-1, 72,
	7, 16,
	-2, 2,
	-1, 73,
	7, 17,
	-2, 42,
	-1, 102,
	7, 17,
	-2, 41,
	-1, 106,
	7, 17,
	-2, 39,
}

const yyPrivate = 57344

const yyLast = 178

var yyAct = [...]int8{
	2, 84, 74, 19, 99, 100, 93, 14, 20, 21,
	22, 23, 24, 25, 15, 26, 27, 28, 29, 16,
	17, 30, 31, 32, 18, 51, 85, 78, 79, 66,
	67, 97, 57, 104, 12, 68, 105, 68, 41, 40,
	62, 19, 54, 33, 61, 14, 20, 21, 106, 23,
	24, 25, 15, 26, 27, 28, 29, 16, 17, 30,
	31, 32, 18, 42, 11, 54, 65, 53, 56, 55,
	46, 92, 12, 91, 89, 77, 64, 34, 44, 45,
	49, 96, 90, 87, 88, 48, 43, 86, 101, 52,
	19, 107, 108, 103, 14, 20, 21, 102, 23, 24,
	25, 15, 26, 27, 28, 29, 16, 17, 30, 31,
	32, 18, 94, 95, 82, 83, 80, 81, 19, 69,
	70, 12, 14, 75, 72, 73, 23, 24, 25, 15,
	26, 27, 28, 29, 16, 17, 30, 31, 32, 18,
	60, 59, 76, 63, 47, 98, 19, 50, 58, 12,
	35, 20, 21, 22, 23, 24, 36, 37, 26, 27,
	28, 29, 38, 39, 30, 31, 32, 13, 71, 10,
	9, 8, 7, 6, 5, 4, 3, 1,
}

var yyPact = [...]int16{
	-1000, -1000, -1, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 36, 142, 34, 66, 140, 80, 75, 61, -1000,
	-1000, -1000, -1000, -1000, -1000, 46, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 25, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 136, -1000, 10, 139, -1000, -1000, -1000, -1000,
	38, 3, 115, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 114, 138, 70, 1, 112, 110, -4, 83, -1000,
	-1000, 73, -1000, -1000, -1000, 66, -25, -1000, 108, -4,
	-1000, -1000, -1000, -1000, -1000, 0, -1000, -1000, -1000, -1000,
	66, 86, -1000, -1000, -1000, -1000, -1000, -1000, 2, -1000,
	-1000, 37, -1000, -1, -1000, 87, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 177, 0, 176, 175, 174, 173, 172, 171, 170,
	169, 168, 2, 71, 167, 64, 148, 147, 25, 1,
	145,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 4, 4, 15, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
	15, 5, 5, 5, 16, 16, 14, 14, 14, 6,
	6, 6, 6, 11, 11, 12, 13, 13, 13, 7,
	8, 9, 10, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 17, 18, 18, 19, 19, 20,
	20, 20, 20,
}

var yyR2 = [...]int8{
	0, 1, 0, 2, 1, 1, 1, 1, 1, 1,
	1, 2, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 2, 3, 1, 1, 1, 2, 2, 7,
	5, 6, 4, 1, 2, 3, 4, 3, 1, 2,
	2, 2, 1, 2, 4, 4, 5, 5, 4, 5,
	3, 3, 4, 4, 1, 1, 3, 2, 3, 1,
	1, 3, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	-10, -15, 35, -14, 8, 15, 20, 21, 25, 4,
	9, 10, 11, 12, 13, 14, 16, 17, 18, 19,
	22, 23, 24, 7, -15, 8, 14, 15, 20, 21,
	5, 4, 29, -13, 12, 13, 4, 4, 5, 5,
	-17, -18, 28, 6, 4, 23, 22, 7, -16, 5,
	4, -2, 30, 4, -18, 28, 26, 27, 34, 4,
	5, -11, 10, 11, -12, 9, 4, 5, 26, 27,
	4, 5, 4, 5, -19, 30, 4, 10, 11, -12,
	9, -2, -13, 31, 4, 5, -19, 31, -20, 4,
	5, -2, 11, -2, 31, 34, 11, 4, 5,
}

var yyDef = [...]int8{
	2, -2, 1, 3, 4, 5, 6, 7, 8, 9,
	10, 0, 0, 0, 14, 21, 26, 27, 52, 13,
	15, 16, 17, 18, 19, -2, 22, 23, 24, 25,
	28, 29, 30, 11, 0, 14, 20, 21, 26, 27,
	31, 32, 0, 2, 0, 0, 48, 49, 50, 51,
	53, 0, 0, 64, 65, 37, 38, 12, 33, 34,
	35, 0, 0, 0, 0, 0, 0, 0, 0, 60,
	61, 0, -2, -2, 43, 15, 0, 47, 0, 0,
	62, 63, 54, 55, 58, 0, 66, 2, 40, 44,
	0, 0, 2, 46, 56, 57, 59, 67, 0, 69,
	70, 0, -2, 0, 68, 0, -2, 71, 72,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:111
		{
			yylex.(*parser).result = yyDollar[1].stmts
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:117
		{
			yyVAL.stmts = []Statement{}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:121
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:127
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:131
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:135
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:139
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:143
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:147
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:151
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:157
		{
			// The value is stored in $2 (ASSIGN token's Lit field)
			yyVAL.stmt = &Assignment{
				Name:  yyDollar[1].str,
				Value: yyDollar[2].str,
			}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:165
		{
			// +Attribute = expr - ClassAd expression to be integrated into job
			// Strip the + prefix and mark as ClassAd expression
			yyVAL.stmt = &Assignment{
				Name:        yyDollar[2].str,
				Value:       yyDollar[3].str,
				ClassAdExpr: true,
			}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:177
		{
			yyVAL.str = yyDollar[1].str
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:180
		{
			yyVAL.str = yyDollar[1].str
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:181
		{
			yyVAL.str = yyDollar[1].str
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:182
		{
			yyVAL.str = yyDollar[1].str
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:183
		{
			yyVAL.str = yyDollar[1].str
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:184
		{
			yyVAL.str = yyDollar[1].str
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:185
		{
			yyVAL.str = yyDollar[1].str
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:186
		{
			yyVAL.str = yyDollar[1].str
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:187
		{
			yyVAL.str = yyDollar[1].str
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:188
		{
			yyVAL.str = yyDollar[1].str
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:189
		{
			yyVAL.str = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:190
		{
			yyVAL.str = yyDollar[1].str
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:191
		{
			yyVAL.str = yyDollar[1].str
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:192
		{
			yyVAL.str = yyDollar[1].str
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:193
		{
			yyVAL.str = yyDollar[1].str
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:194
		{
			yyVAL.str = yyDollar[1].str
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:195
		{
			yyVAL.str = yyDollar[1].str
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:196
		{
			yyVAL.str = yyDollar[1].str
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:200
		{
			yyVAL.stmt = &IncludeDirective{
				Type: yyDollar[1].str,
				Path: yyDollar[2].str,
			}
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:207
		{
			yyVAL.stmt = &IncludeDirective{
				Type: yyDollar[1].str,
				Path: yyDollar[2].str,
			}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:214
		{
			// Check if path ends with | to determine if it's a command
			path := yyDollar[3].str
			inclType := yyDollar[1].str
			if len(path) > 0 && path[len(path)-1] == '|' {
				// Remove trailing | and mark as command
				path = strings.TrimSpace(path[:len(path)-1])
				if inclType == "include" {
					inclType = "include_command"
				} else if inclType == "include_ifexist" {
					inclType = "include_ifexist_command"
				}
			}
			yyVAL.stmt = &IncludeDirective{
				Type: inclType,
				Path: path,
			}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:235
		{
			yyVAL.str = yyDollar[1].str
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:239
		{
			yyVAL.str = yyDollar[1].str
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:245
		{
			yyVAL.str = "include"
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:249
		{
			yyVAL.str = "include_command"
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:253
		{
			yyVAL.str = "include_ifexist"
		}
	case 39:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:259
		{
			yyVAL.stmt = &Conditional{
				Condition:   yyDollar[2].str,
				ThenBlock:   yyDollar[3].stmts,
				ElseIfBlock: yyDollar[4].elseifs,
				ElseBlock:   yyDollar[6].stmts,
			}
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:268
		{
			yyVAL.stmt = &Conditional{
				Condition:   yyDollar[2].str,
				ThenBlock:   yyDollar[3].stmts,
				ElseIfBlock: yyDollar[4].elseifs,
				ElseBlock:   nil,
			}
		}
	case 41:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:277
		{
			yyVAL.stmt = &Conditional{
				Condition:   yyDollar[2].str,
				ThenBlock:   yyDollar[3].stmts,
				ElseIfBlock: nil,
				ElseBlock:   yyDollar[5].stmts,
			}
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:286
		{
			yyVAL.stmt = &Conditional{
				Condition:   yyDollar[2].str,
				ThenBlock:   yyDollar[3].stmts,
				ElseIfBlock: nil,
				ElseBlock:   nil,
			}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:297
		{
			yyVAL.elseifs = []ElseIf{yyDollar[1].elseif}
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:301
		{
			yyVAL.elseifs = append(yyDollar[1].elseifs, yyDollar[2].elseif)
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:307
		{
			yyVAL.elseif = ElseIf{
				Condition: yyDollar[2].str,
				Block:     yyDollar[3].stmts,
			}
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:316
		{
			yyVAL.str = fmt.Sprintf("defined(%s)", yyDollar[3].str)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:320
		{
			yyVAL.str = fmt.Sprintf("version %s %s", yyDollar[2].str, yyDollar[3].str)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:324
		{
			yyVAL.str = yyDollar[1].str
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:330
		{
			yyVAL.stmt = &UseDirective{
				Role: yyDollar[2].str,
			}
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:338
		{
			yyVAL.stmt = &ErrorDirective{
				Message: yyDollar[2].str,
			}
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:346
		{
			yyVAL.stmt = &WarningDirective{
				Message: yyDollar[2].str,
			}
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:354
		{
			// Simple "queue" with default count of 1
			yyVAL.stmt = &QueueStatement{
				Count: 1,
			}
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:361
		{
			// "queue N" - queue N jobs
			yyVAL.stmt = &QueueStatement{
				Count: yyDollar[2].intval,
			}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:368
		{
			// "queue var1, var2 from file"
			yyVAL.stmt = &QueueStatement{
				Count:    0, // Determined by file
				VarNames: yyDollar[2].strlist,
				File:     yyDollar[4].str,
			}
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:377
		{
			// "queue var1, var2 from file" (with quoted path)
			yyVAL.stmt = &QueueStatement{
				Count:    0, // Determined by file
				VarNames: yyDollar[2].strlist,
				File:     yyDollar[4].str,
			}
		}
	case 56:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:386
		{
			// "queue N var1, var2 from file"
			yyVAL.stmt = &QueueStatement{
				Count:    yyDollar[2].intval,
				VarNames: yyDollar[3].strlist,
				File:     yyDollar[5].str,
			}
		}
	case 57:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:395
		{
			// "queue N var1, var2 from file" (with quoted path)
			yyVAL.stmt = &QueueStatement{
				Count:    yyDollar[2].intval,
				VarNames: yyDollar[3].strlist,
				File:     yyDollar[5].str,
			}
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:404
		{
			// "queue var in (item1, item2, item3)"
			yyVAL.stmt = &QueueStatement{
				Count:    0, // Determined by item count
				VarNames: yyDollar[2].strlist,
				Items:    yyDollar[4].strlist,
			}
		}
	case 59:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:413
		{
			// "queue N var in (item1, item2)"
			yyVAL.stmt = &QueueStatement{
				Count:    yyDollar[2].intval,
				VarNames: yyDollar[3].strlist,
				Items:    yyDollar[5].strlist,
			}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:422
		{
			// "queue matching pattern"
			yyVAL.stmt = &QueueStatement{
				Count: 0,               // Determined by matches
				File:  yyDollar[3].str, // Pattern stored in File field
			}
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:430
		{
			// "queue matching pattern" (with quoted pattern)
			yyVAL.stmt = &QueueStatement{
				Count: 0,               // Determined by matches
				File:  yyDollar[3].str, // Pattern stored in File field
			}
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:438
		{
			// "queue N matching pattern"
			yyVAL.stmt = &QueueStatement{
				Count: yyDollar[2].intval,
				File:  yyDollar[4].str, // Pattern stored in File field
			}
		}
	case 63:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:446
		{
			// "queue N matching pattern" (with quoted pattern)
			yyVAL.stmt = &QueueStatement{
				Count: yyDollar[2].intval,
				File:  yyDollar[4].str, // Pattern stored in File field
			}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:456
		{
			// Convert string number to int
			var count int
			fmt.Sscanf(yyDollar[1].str, "%d", &count)
			yyVAL.intval = count
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:465
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:469
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:475
		{
			yyVAL.strlist = []string{}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:479
		{
			yyVAL.strlist = yyDollar[2].strlist
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:485
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:489
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:493
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:497
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	}
	goto yystack /* stack new state and value */
}
